name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Remove cargo config for incremental builds (Linux & macOS)
      run: rm -f .cargo/config.toml
      if: runner.os != 'windows'

    - name: Install alsa and udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends g++ pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      if: runner.os == 'linux'

    - name: Build gen_move_tab
      run: cargo build --verbose --bin gen_move_tab

    - name: Build demo
      run: cargo build --verbose --bin demo

    - name: Build konego
      run: cargo build --verbose --bin konego

    - name: Run tests
      run: cargo test --verbose

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Remove cargo config for incremental builds
        run: rm -f .cargo/config.toml

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check
