name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build nego
      run: cargo build --verbose --bin nego
    - name: Build konego
      run: cargo build --verbose --bin konego
    - name: Build gen_move_tab
      run: cargo build --verbose --bin gen_move_tab
    - name: Run tests
      run: cargo test --verbose
